Repository stackabletech/regorule-operator, pull requests merged in 2021-05, with the labels that each got.

#7 Remove redundant release build and introduce caching
  .github/workflows/rust.yml
Labels: priority/low, size/XS, type/enhancement

#8 Added clean command to rust build.
  .github/workflows/rust.yml
Labels: type/enhancement

#16 Add example for is_minute_even
  examples/simple-regorule-is-minute-even.yaml
Labels: priority/high, size/S, type/enhancement

#19 Fix service path for RHEL
  server/packaging/rpm/SOURCES/stackable-regorule-operator-server-VERSION/usr/lib/systemd/system/stackable-regorule-operator-server.service
Labels: priority/critical, size/XS, type/bug

#26 Bring operator up to best practices
  .github/dependabot.yml
  .github/workflows/build_artifacts.yml
  .github/workflows/daily_security.yml
  .github/workflows/rust.yml
  Cargo.lock
  crd/Cargo.toml
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/building.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/usage.adoc
  operator/Cargo.toml
  server/Cargo.toml
  server/src/bin/generate_regorule_crd.rs
  server/src/main.rs
Labels: priority/low, type/enhancement
